agent:
  class: sac

  actor:
    class: soft-gaussian
    encoder:
      class: cnn
      args:
        input_dim: null
        output_dim: 50
        filters: [5,10]
        kernels: [3,3]
        strides: [2,2]
        paddings: [2,2]
        dilations: [1,1]
        conv_norm: null
        conv_act: relu
        conv_drop_rate: 0.0
        out_norm: null
        out_act: tanh
        out_drop_rate: 0.0
    network:
      class: dense
      args:
        input_dim: null
        output_dim: null
        hidden_nodes: [64,64]
        fc_norm: null
        fc_act: relu
        fc_drop_rate: 0.0
        out_norm: null
        out_act: null
        out_drop_rate: 0.0
    optimizer:
      class: adam
      args:
        betas: [0.9,0.999]
        lr: 0.005

  critic:
    class: continuous-double-shared-encoder # [continuous-double-shared-encoder, continuous-double]
    encoder:
      class: cnn
      args:
        input_dim: null
        output_dim: 50
        filters: [5,10]
        kernels: [3,3]
        strides: [2,2]
        paddings: [2,2]
        dilations: [1,1]
        conv_norm: null
        conv_act: relu
        conv_drop_rate: 0.0
        out_norm: null
        out_act: tanh
        out_drop_rate: 0.0
    network:
      class: dense
      args:
        input_dim: null
        output_dim: null
        hidden_nodes: [64,64]
        fc_norm: null
        fc_act: relu
        fc_drop_rate: 0.0
        out_norm: null
        out_act: null
        out_drop_rate: 0.0
    optimizer:
      class: adam
      args:
        betas: [0.9,0.999]
        lr: 0.005

  args:
    critic_tau: 0.005
    critic_grad_clip: 20.0
    actor_grad_clip: 20.0
    gamma: 0.99
    n_steps: 1
    alpha: 0.2
    alpha_auto_tune: true
    alpha_lr: 0.0001
    target_entropy: -2.
    target_update_freq: 2
    actor_update_freq: 2
    shared_encoder: false

  buffer:
    demos: true
    prioritized: true
    use_disk: false
    args:
      replay_capacity: 100000
      history_len: 1
      n_steps: 1
      batch_size: 32
      gamma: 0.99
      max_sample_attempts: 10000


environment:
  class: rlbench
  task: reach-target
  action: 0
  gripper_action: 0
  observation:
    image_size: [64, 64]
    joint_positions: true
    joint_velocities: true
    gripper_pose: true
    gripper_open: true
    front_rgb: true
    wrist_rgb: true
    low_dim: false
  args:
    robot_config: ur3baxter 
    task_variation: 0
    fixed_variation: true
    headless: true
    normalize_vision: true
    max_episode_steps: 500


framework:
  exp_name: tmp
  alg_name: sac
  env_name: reach-target-easy
  cpu: false
  logdir: ./logs/
  log_freq: 100
  save_freq: 100
  tensorboard_logging: true
  csv_logging: true
  action_repeat: 1
  max_frames: 4000000
  max_iterations: 40000
  replay_ratio: 128
  transitions_before_train: 200
  num_train_envs: 1
  num_eval_envs: 1
  seeds: 1