class: id
kwargs:


class: dense
kwargs:
  input_dim: null
  output_dim: null
  hidden_nodes: [64,64]
  fc_norm: null
  fc_act: relu
  fc_drop_rate: 0.0
  out_norm: null
  out_act: null
  out_drop_rate: 0.0


class: cnn
kwargs:
  input_dim: null
  output_dim: 50
  filters: [5,10]
  kernels: [3,3]
  strides: [2,2]
  paddings: [2,2]
  dilations: [1,1]
  conv_norm: null
  conv_act: relu
  conv_drop_rate: 0.0
  out_norm: null
  out_act: tanh
  out_drop_rate: 0.0


class: custom
kwargs:
  input_dim: null
  output_dim: 256
  module: null # (TODO this is very ugly it should be changed) the module path should be in general/custom_net 
  object:
    class: Encoder # name of the class in the module
    kwargs: # varies for each class
      weight: /home/caor/Documents/rlfarm/logs_vision/push-depth-DA/bestModel.pth
# general:
#   custom_net: ./rlfarm/networks/custom/custom_resnet.py
